services:
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink
    restart: unless-stopped
    volumes:
      - ./lavalink/lavalink.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    expose:
      - "2333"
  spotify-tokener:
    image: ghcr.io/topi314/spotify-tokener:master
    container_name: spotify-tokener
    restart: unless-stopped
    environment:
      - SPOTIFY_TOKENER_ADDR=0.0.0.0:8080
      - SPOTIFY_TOKENER_LOG_LEVEL=INFO
    ports:
      - 8080:8080
  mongo:
    container_name: mongo
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ./mongo:/data/db
    expose:
      - "27017"
    secrets:
      - db_password
  cdn-script:
    container_name: cdn-script
    build:
      context: .
      dockerfile: cdn-script.Dockerfile
    expose:
      - "8081"
  nginx:
    container_name: image-server
    image: nginx:mainline-alpine3.22-perl
    volumes:
      - ./largefiles:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  cade:
    container_name: cade
    build: .
    environment:
      - GENERATE=false
    volumes:
      - ./cade/commands.md:/cade/cade/commands.md
      - ./largefiles:/cade/largefiles
    depends_on:
      - cdn-script
      - lavalink
      - mongo
secrets:
  db_password:
    file: db_password.txt